export const MUTATE_TODO_LIST = 'MUTATE_TODO_LIST'
export const CLEAR_TODO_LIST = 'CLEAR_TODO_LIST'

export const SHOW_CLEAR_TODO_LIST_CONFIRMATION_POPUP = 'SHOW_CLEAR_TODO_LIST_CONFIRMATION_POPUP'
export const HIDE_CLEAR_TODO_LIST_CONFIRMATION_POPUP = 'HIDE_CLEAR_TODO_LIST_CONFIRMATION_POPUP'

export const SHOW_EDIT_TODO_POPUP = 'SHOW_EDIT_TODO_POPUP'
export const HIDE_EDIT_TODO_POPUP = 'HIDE_EDIT_TODO_POPUP'